# Generated by Django 5.1.1 on 2024-09-10 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_remove_exam_created_at_remove_question_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='choice_text',
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='main.category'),
        ),
    ]
