# Generated by Django 5.1.2 on 2025-08-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_choice_choice_image_question_question_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
